// <auto-generated />
using System;
using Collectly.API.Base;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Collectly.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20200220003107_CTL_200219")]
    partial class CTL_200219
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Collectly.API.Collections.CollectionData", b =>
                {
                    b.Property<long>("CollectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("CollectionID");

                    b.ToTable("collectly_v5_dataCollections");
                });

            modelBuilder.Entity("Collectly.API.Layouts.LayoutData", b =>
                {
                    b.Property<long>("LayoutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("LayoutID");

                    b.ToTable("collectly_v5_dataLayouts");
                });

            modelBuilder.Entity("Collectly.API.Layouts.LayoutTagData", b =>
                {
                    b.Property<long>("LayoutTagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("LayoutID")
                        .HasColumnType("bigint");

                    b.Property<bool>("Multiple")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasMaxLength(500);

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("LayoutTagID");

                    b.HasIndex("LayoutID")
                        .HasName("collectly_v5_dataLayoutTags_index_Layout")
                        .HasAnnotation("SqlServer:Include", new[] { "LayoutTagID" });

                    b.ToTable("collectly_v5_dataLayoutTags");
                });

            modelBuilder.Entity("Collectly.API.Layouts.LayoutTagData", b =>
                {
                    b.HasOne("Collectly.API.Layouts.LayoutData", "LayoutDetails")
                        .WithMany()
                        .HasForeignKey("LayoutID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
